name: Build Flet APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"

      - name: Install Flet CLI
        run: pip install flet

      # يبني APK مستقل من main.py (Python + Flutter معًا)
      - name: Build APK with Flet
        run: flet build apk main.py

      # (اختياري) يبني AAB أيضًا
      - name: Build AAB with Flet
        run: flet build aab main.py

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: "build/flet/*.apk"

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: flet-aab
          path: "build/flet/*.aab"      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: flet-aab
          path: build/app/outputs/bundle/release/app-release.aab          path: build/flet/*.apk
